In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/playground-series-s3e17/sample_submission.csv
/kaggle/input/playground-series-s3e17/train.csv
/kaggle/input/playground-series-s3e17/test.csv

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [3]:
df = pd.read_csv('/kaggle/input/playground-series-s3e17/train.csv',index_col=0)
df

,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
id,,,,,,,,,,,,,
0,L50096,L,300.6,309.6,1596,36.1,140,0,0,0,0,0,0
1,M20343,M,302.6,312.1,1759,29.1,200,0,0,0,0,0,0
2,L49454,L,299.3,308.5,1805,26.5,25,0,0,0,0,0,0
3,L53355,L,301.0,310.9,1524,44.3,197,0,0,0,0,0,0
4,M24050,M,298.0,309.0,1641,35.4,34,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136424,M22284,M,300.1,311.4,1530,37.5,210,0,0,0,0,0,0
136425,H38017,H,297.5,308.5,1447,49.1,2,0,0,0,0,0,0
136426,L54690,L,300.5,311.8,1524,38.5,214,0,0,0,0,0,0
136427,L53876,L,301.7,310.9,1447,46.3,42,0,0,0,0,0,0
136428,L47937,L,296.9,308.1,1557,39.3,229,0,0,0,0,0,0

In [4]:
Type = pd.get_dummies(df["Type"],drop_first=True)
print(Type)

        L  M
id
0       1  0
1       0  1
2       1  0
3       1  0
4       0  1
...    .. ..
136424  0  1
136425  0  0
136426  1  0
136427  1  0
136428  1  0

[136429 rows x 2 columns]

In [5]:
df1 = df.drop('Type',axis=1)
df1.head()

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
id,,,,,,,,,,,,
0,L50096,300.6,309.6,1596,36.1,140,0,0,0,0,0,0
1,M20343,302.6,312.1,1759,29.1,200,0,0,0,0,0,0
2,L49454,299.3,308.5,1805,26.5,25,0,0,0,0,0,0
3,L53355,301.0,310.9,1524,44.3,197,0,0,0,0,0,0
4,M24050,298.0,309.0,1641,35.4,34,0,0,0,0,0,0

In [6]:
df1 = pd.concat([df1,Type],axis=1)
df1

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,L,M
id,,,,,,,,,,,,,,
0,L50096,300.6,309.6,1596,36.1,140,0,0,0,0,0,0,1,0
1,M20343,302.6,312.1,1759,29.1,200,0,0,0,0,0,0,0,1
2,L49454,299.3,308.5,1805,26.5,25,0,0,0,0,0,0,1,0
3,L53355,301.0,310.9,1524,44.3,197,0,0,0,0,0,0,1,0
4,M24050,298.0,309.0,1641,35.4,34,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136424,M22284,300.1,311.4,1530,37.5,210,0,0,0,0,0,0,0,1
136425,H38017,297.5,308.5,1447,49.1,2,0,0,0,0,0,0,0,0
136426,L54690,300.5,311.8,1524,38.5,214,0,0,0,0,0,0,1,0
136427,L53876,301.7,310.9,1447,46.3,42,0,0,0,0,0,0,1,0
136428,L47937,296.9,308.1,1557,39.3,229,0,0,0,0,0,0,1,0

In [7]:
df2 = df1.copy()
df2.head()

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,L,M
id,,,,,,,,,,,,,,
0,L50096,300.6,309.6,1596,36.1,140,0,0,0,0,0,0,1,0
1,M20343,302.6,312.1,1759,29.1,200,0,0,0,0,0,0,0,1
2,L49454,299.3,308.5,1805,26.5,25,0,0,0,0,0,0,1,0
3,L53355,301.0,310.9,1524,44.3,197,0,0,0,0,0,0,1,0
4,M24050,298.0,309.0,1641,35.4,34,0,0,0,0,0,0,0,1

In [8]:
df2['Product ID']=df2['Product ID'].str[1:]

In [9]:
df2

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF,L,M
id,,,,,,,,,,,,,,
0,50096,300.6,309.6,1596,36.1,140,0,0,0,0,0,0,1,0
1,20343,302.6,312.1,1759,29.1,200,0,0,0,0,0,0,0,1
2,49454,299.3,308.5,1805,26.5,25,0,0,0,0,0,0,1,0
3,53355,301.0,310.9,1524,44.3,197,0,0,0,0,0,0,1,0
4,24050,298.0,309.0,1641,35.4,34,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136424,22284,300.1,311.4,1530,37.5,210,0,0,0,0,0,0,0,1
136425,38017,297.5,308.5,1447,49.1,2,0,0,0,0,0,0,0,0
136426,54690,300.5,311.8,1524,38.5,214,0,0,0,0,0,0,1,0
136427,53876,301.7,310.9,1447,46.3,42,0,0,0,0,0,0,1,0
136428,47937,296.9,308.1,1557,39.3,229,0,0,0,0,0,0,1,0

In [10]:
df_test = pd.read_csv('/kaggle/input/playground-series-s3e17/test.csv',index_col=0)
df_test.head()

,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],TWF,HDF,PWF,OSF,RNF
id,,,,,,,,,,,,
136429,L50896,L,302.3,311.5,1499,38.0,60,0,0,0,0,0
136430,L53866,L,301.7,311.0,1713,28.8,17,0,0,0,0,0
136431,L50498,L,301.3,310.4,1525,37.7,96,0,0,0,0,0
136432,M21232,M,300.1,309.6,1479,47.6,5,0,0,0,0,0
136433,M19751,M,303.4,312.3,1515,41.3,114,0,0,0,0,0

In [11]:
Type_test = pd.get_dummies(df_test["Type"],drop_first=True)

In [12]:
df_test = df_test.drop('Type',axis=1)
df_test.head()

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],TWF,HDF,PWF,OSF,RNF
id,,,,,,,,,,,
136429,L50896,302.3,311.5,1499,38.0,60,0,0,0,0,0
136430,L53866,301.7,311.0,1713,28.8,17,0,0,0,0,0
136431,L50498,301.3,310.4,1525,37.7,96,0,0,0,0,0
136432,M21232,300.1,309.6,1479,47.6,5,0,0,0,0,0
136433,M19751,303.4,312.3,1515,41.3,114,0,0,0,0,0

In [13]:
df_test = pd.concat([df_test,Type_test],axis=1)
df_test

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],TWF,HDF,PWF,OSF,RNF,L,M
id,,,,,,,,,,,,,
136429,L50896,302.3,311.5,1499,38.0,60,0,0,0,0,0,1,0
136430,L53866,301.7,311.0,1713,28.8,17,0,0,0,0,0,1,0
136431,L50498,301.3,310.4,1525,37.7,96,0,0,0,0,0,1,0
136432,M21232,300.1,309.6,1479,47.6,5,0,0,0,0,0,0,1
136433,M19751,303.4,312.3,1515,41.3,114,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
227378,L51130,302.3,311.4,1484,40.4,15,0,0,0,0,0,1,0
227379,L47783,297.9,309.8,1542,33.8,31,0,0,0,0,0,1,0
227380,L48097,295.6,306.2,1501,41.4,187,0,0,0,0,0,1,0
227381,L48969,298.1,307.8,1534,40.3,69,0,0,0,0,0,1,0
227382,L52525,303.5,312.8,1534,36.1,92,0,0,0,0,0,1,0

In [14]:
df_test['Product ID']=df_test['Product ID'].str[1:]

In [15]:
df_test

,Product ID,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],TWF,HDF,PWF,OSF,RNF,L,M
id,,,,,,,,,,,,,
136429,50896,302.3,311.5,1499,38.0,60,0,0,0,0,0,1,0
136430,53866,301.7,311.0,1713,28.8,17,0,0,0,0,0,1,0
136431,50498,301.3,310.4,1525,37.7,96,0,0,0,0,0,1,0
136432,21232,300.1,309.6,1479,47.6,5,0,0,0,0,0,0,1
136433,19751,303.4,312.3,1515,41.3,114,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
227378,51130,302.3,311.4,1484,40.4,15,0,0,0,0,0,1,0
227379,47783,297.9,309.8,1542,33.8,31,0,0,0,0,0,1,0
227380,48097,295.6,306.2,1501,41.4,187,0,0,0,0,0,1,0
227381,48969,298.1,307.8,1534,40.3,69,0,0,0,0,0,1,0
227382,52525,303.5,312.8,1534,36.1,92,0,0,0,0,0,1,0

In [16]:
df2['Machine failure'].value_counts()

0    134281
1      2148
Name: Machine failure, dtype: int64

In [17]:
X = df2.drop("Machine failure", axis="columns")
y = df2["Machine failure"]

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=10000, random_state=0)

In [19]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold

lr = LogisticRegression(solver="liblinear")
params = {
    "C":[0.1, 1.0, 10.0],
    "penalty":["l1", "l2"]
}
cv = KFold(n_splits=5)
scoring = "roc_auc"
gs = GridSearchCV(lr, param_grid=params, cv=cv, scoring=scoring)

In [20]:
gs.fit(X_train,y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(solver='liblinear'),
             param_grid={'C': [0.1, 1.0, 10.0], 'penalty': ['l1', 'l2']},
             scoring='roc_auc')

In [21]:
gs.best_params_

{'C': 10.0, 'penalty': 'l1'}

In [22]:
gs.best_score_

0.9278479215751219

In [23]:
y_test_pred = gs.predict(df_test)
y_test_proba = gs.predict_proba(df_test)

In [24]:
df_test_id = df_test.index
X_test_ = pd.Series(df_test_id)
X_test_

0        136429
1        136430
2        136431
3        136432
4        136433
          ...
90949    227378
90950    227379
90951    227380
90952    227381
90953    227382
Name: id, Length: 90954, dtype: int64

In [25]:
y_test_ = pd.Series(y_test_proba[:,1],name='Machine failure')
y_test_

0        0.001753
1        0.000784
2        0.002242
3        0.002882
4        0.002448
           ...
90949    0.001811
90950    0.001323
90951    0.006195
90952    0.003221
90953    0.001595
Name: Machine failure, Length: 90954, dtype: float64

In [26]:
submission = pd.concat([X_test_,y_test_],axis=1)

In [27]:
submission

           id  Machine failure
0      136429         0.001753
1      136430         0.000784
2      136431         0.002242
3      136432         0.002882
4      136433         0.002448
...       ...              ...
90949  227378         0.001811
90950  227379         0.001323
90951  227380         0.006195
90952  227381         0.003221
90953  227382         0.001595

[90954 rows x 2 columns]

In [28]:
submission.to_csv('submission.csv',index=None)